VIRTUAL_KEY_MAP virtual_key_bitmask[VIRTUAL_KEY_NUM] = {
	{ 1ull << VIRTUAL_KEY_LBUTTON, 0 },
	{ 1ull << VIRTUAL_KEY_RBUTTON, 0 },
	{ 1ull << VIRTUAL_KEY_CANCEL, 0 },
	{ 1ull << VIRTUAL_KEY_MBUTTON, 0 },
	{ 1ull << VIRTUAL_KEY_XBUTTON1, 0 },
	{ 1ull << VIRTUAL_KEY_XBUTTON2, 0 },
	{ 1ull << VIRTUAL_KEY_BACK, 0 },
	{ 1ull << VIRTUAL_KEY_TAB, 0 },
	{ 1ull << VIRTUAL_KEY_CLEAR, 0 },
	{ 1ull << VIRTUAL_KEY_RETURN, 0 },
	{ 1ull << VIRTUAL_KEY_SHIFT, 0 },
	{ 1ull << VIRTUAL_KEY_CONTROL, 0 },
	{ 1ull << VIRTUAL_KEY_MENU, 0 },
	{ 1ull << VIRTUAL_KEY_PAUSE, 0 },
	{ 1ull << VIRTUAL_KEY_CAPITAL, 0 },
	{ 1ull << VIRTUAL_KEY_HANGUL, 0 },
	{ 1ull << VIRTUAL_KEY_IME_ON, 0 },
	{ 1ull << VIRTUAL_KEY_JUNJA, 0 },
	{ 1ull << VIRTUAL_KEY_FINAL, 0 },
	{ 1ull << VIRTUAL_KEY_HANJA, 0 },
	{ 1ull << VIRTUAL_KEY_KANJI, 0 },
	{ 1ull << VIRTUAL_KEY_IME_OFF, 0 },
	{ 1ull << VIRTUAL_KEY_ESCAPE, 0 },
	{ 1ull << VIRTUAL_KEY_CONVERT, 0 },
	{ 1ull << VIRTUAL_KEY_NONCONVERT, 0 },
	{ 1ull << VIRTUAL_KEY_ACCEPT, 0 },
	{ 1ull << VIRTUAL_KEY_MODECHANGE, 0 },
	{ 1ull << VIRTUAL_KEY_SPACE, 0 },
	{ 1ull << VIRTUAL_KEY_PRIOR, 0 },
	{ 1ull << VIRTUAL_KEY_NEXT, 0 },
	{ 1ull << VIRTUAL_KEY_END, 0 },
	{ 1ull << VIRTUAL_KEY_HOME, 0 },
	{ 1ull << VIRTUAL_KEY_LEFT, 0 },
	{ 1ull << VIRTUAL_KEY_UP, 0 },
	{ 1ull << VIRTUAL_KEY_RIGHT, 0 },
	{ 1ull << VIRTUAL_KEY_DOWN, 0 },
	{ 1ull << VIRTUAL_KEY_SELECT, 0 },
	{ 1ull << VIRTUAL_KEY_PRINT, 0 },
	{ 1ull << VIRTUAL_KEY_EXECUTE, 0 },
	{ 1ull << VIRTUAL_KEY_SNAPSHOT, 0 },
	{ 1ull << VIRTUAL_KEY_INSERT, 0 },
	{ 1ull << VIRTUAL_KEY_DELETE, 0 },
	{ 1ull << VIRTUAL_KEY_HELP, 0 },
	{ 1ull << VIRTUAL_KEY_0, 0 },
	{ 1ull << VIRTUAL_KEY_1, 0 },
	{ 1ull << VIRTUAL_KEY_2, 0 },
	{ 1ull << VIRTUAL_KEY_3, 0 },
	{ 1ull << VIRTUAL_KEY_4, 0 },
	{ 1ull << VIRTUAL_KEY_5, 0 },
	{ 1ull << VIRTUAL_KEY_6, 0 },
	{ 1ull << VIRTUAL_KEY_7, 0 },
	{ 1ull << VIRTUAL_KEY_8, 0 },
	{ 1ull << VIRTUAL_KEY_9, 0 },
	{ 1ull << VIRTUAL_KEY_A, 0 },
	{ 1ull << VIRTUAL_KEY_B, 0 },
	{ 1ull << VIRTUAL_KEY_C, 0 },
	{ 1ull << VIRTUAL_KEY_D, 0 },
	{ 1ull << VIRTUAL_KEY_E, 0 },
	{ 1ull << VIRTUAL_KEY_F, 0 },
	{ 1ull << VIRTUAL_KEY_G, 0 },
	{ 1ull << VIRTUAL_KEY_H, 0 },
	{ 1ull << VIRTUAL_KEY_I, 0 },
	{ 1ull << VIRTUAL_KEY_J, 0 },
	{ 1ull << VIRTUAL_KEY_K, 0 },
	{ 0, 1ull << (static_cast<uint64_t>(VIRTUAL_KEY_L) - 64) },
	{ 0, 1ull << (static_cast<uint64_t>(VIRTUAL_KEY_M) - 64) },
	{ 0, 1ull << (static_cast<uint64_t>(VIRTUAL_KEY_N) - 64) },
	{ 0, 1ull << (static_cast<uint64_t>(VIRTUAL_KEY_O) - 64) },
	{ 0, 1ull << (static_cast<uint64_t>(VIRTUAL_KEY_P) - 64) },
	{ 0, 1ull << (static_cast<uint64_t>(VIRTUAL_KEY_Q) - 64) },
	{ 0, 1ull << (static_cast<uint64_t>(VIRTUAL_KEY_R) - 64) },
	{ 0, 1ull << (static_cast<uint64_t>(VIRTUAL_KEY_S) - 64) },
	{ 0, 1ull << (static_cast<uint64_t>(VIRTUAL_KEY_T) - 64) },
	{ 0, 1ull << (static_cast<uint64_t>(VIRTUAL_KEY_U) - 64) },
	{ 0, 1ull << (static_cast<uint64_t>(VIRTUAL_KEY_V) - 64) },
	{ 0, 1ull << (static_cast<uint64_t>(VIRTUAL_KEY_W) - 64) },
	{ 0, 1ull << (static_cast<uint64_t>(VIRTUAL_KEY_X) - 64) },
	{ 0, 1ull << (static_cast<uint64_t>(VIRTUAL_KEY_Y) - 64) },
	{ 0, 1ull << (static_cast<uint64_t>(VIRTUAL_KEY_Z) - 64) },
	{ 0, 1ull << (static_cast<uint64_t>(VIRTUAL_KEY_NUMPAD0) - 64) },
	{ 0, 1ull << (static_cast<uint64_t>(VIRTUAL_KEY_NUMPAD1) - 64) },
	{ 0, 1ull << (static_cast<uint64_t>(VIRTUAL_KEY_NUMPAD2) - 64) },
	{ 0, 1ull << (static_cast<uint64_t>(VIRTUAL_KEY_NUMPAD3) - 64) },
	{ 0, 1ull << (static_cast<uint64_t>(VIRTUAL_KEY_NUMPAD4) - 64) },
	{ 0, 1ull << (static_cast<uint64_t>(VIRTUAL_KEY_NUMPAD5) - 64) },
	{ 0, 1ull << (static_cast<uint64_t>(VIRTUAL_KEY_NUMPAD6) - 64) },
	{ 0, 1ull << (static_cast<uint64_t>(VIRTUAL_KEY_NUMPAD7) - 64) },
	{ 0, 1ull << (static_cast<uint64_t>(VIRTUAL_KEY_NUMPAD8) - 64) },
	{ 0, 1ull << (static_cast<uint64_t>(VIRTUAL_KEY_NUMPAD9) - 64) },
	{ 0, 1ull << (static_cast<uint64_t>(VIRTUAL_KEY_MULTIPLY) - 64) },
	{ 0, 1ull << (static_cast<uint64_t>(VIRTUAL_KEY_ADD) - 64) },
	{ 0, 1ull << (static_cast<uint64_t>(VIRTUAL_KEY_SEPARATOR) - 64) },
	{ 0, 1ull << (static_cast<uint64_t>(VIRTUAL_KEY_SUBTRACT) - 64) },
	{ 0, 1ull << (static_cast<uint64_t>(VIRTUAL_KEY_DECIMAL) - 64) },
	{ 0, 1ull << (static_cast<uint64_t>(VIRTUAL_KEY_DIVIDE) - 64) },
	{ 0, 1ull << (static_cast<uint64_t>(VIRTUAL_KEY_F1) - 64) },
	{ 0, 1ull << (static_cast<uint64_t>(VIRTUAL_KEY_F2) - 64) },
	{ 0, 1ull << (static_cast<uint64_t>(VIRTUAL_KEY_F3) - 64) },
	{ 0, 1ull << (static_cast<uint64_t>(VIRTUAL_KEY_F4) - 64) },
	{ 0, 1ull << (static_cast<uint64_t>(VIRTUAL_KEY_F5) - 64) },
	{ 0, 1ull << (static_cast<uint64_t>(VIRTUAL_KEY_F6) - 64) },
	{ 0, 1ull << (static_cast<uint64_t>(VIRTUAL_KEY_F7) - 64) },
	{ 0, 1ull << (static_cast<uint64_t>(VIRTUAL_KEY_F8) - 64) },
	{ 0, 1ull << (static_cast<uint64_t>(VIRTUAL_KEY_F9) - 64) },
	{ 0, 1ull << (static_cast<uint64_t>(VIRTUAL_KEY_F10) - 64) },
	{ 0, 1ull << (static_cast<uint64_t>(VIRTUAL_KEY_F11) - 64) },
	{ 0, 1ull << (static_cast<uint64_t>(VIRTUAL_KEY_F12) - 64) }
};

std::map<WORD, MOUSE_KEYBOARD_VIRTUAL_KEY> wnd_vk_to_virtual_key = {
	{ VK_LBUTTON, VIRTUAL_KEY_LBUTTON },
	{ VK_RBUTTON, VIRTUAL_KEY_RBUTTON },
	{ VK_CANCEL, VIRTUAL_KEY_CANCEL },
	{ VK_MBUTTON, VIRTUAL_KEY_MBUTTON },
	{ VK_XBUTTON1, VIRTUAL_KEY_XBUTTON1 },
	{ VK_XBUTTON2, VIRTUAL_KEY_XBUTTON2 },
	{ VK_BACK, VIRTUAL_KEY_BACK },
	{ VK_TAB, VIRTUAL_KEY_TAB },
	{ VK_CLEAR, VIRTUAL_KEY_CLEAR },
	{ VK_RETURN, VIRTUAL_KEY_RETURN },
	{ VK_SHIFT, VIRTUAL_KEY_SHIFT },
	{ VK_CONTROL, VIRTUAL_KEY_CONTROL },
	{ VK_MENU, VIRTUAL_KEY_MENU },
	{ VK_PAUSE, VIRTUAL_KEY_PAUSE },
	{ VK_CAPITAL, VIRTUAL_KEY_CAPITAL },
	{ VK_HANGUL, VIRTUAL_KEY_HANGUL },
	{ VK_IME_ON, VIRTUAL_KEY_IME_ON },
	{ VK_JUNJA, VIRTUAL_KEY_JUNJA },
	{ VK_FINAL, VIRTUAL_KEY_FINAL },
	{ VK_HANJA, VIRTUAL_KEY_HANJA },
	{ VK_KANJI, VIRTUAL_KEY_KANJI },
	{ VK_IME_OFF, VIRTUAL_KEY_IME_OFF },
	{ VK_ESCAPE, VIRTUAL_KEY_ESCAPE },
	{ VK_CONVERT, VIRTUAL_KEY_CONVERT },
	{ VK_NONCONVERT, VIRTUAL_KEY_NONCONVERT },
	{ VK_ACCEPT, VIRTUAL_KEY_ACCEPT },
	{ VK_MODECHANGE, VIRTUAL_KEY_MODECHANGE },
	{ VK_SPACE, VIRTUAL_KEY_SPACE },
	{ VK_PRIOR, VIRTUAL_KEY_PRIOR },
	{ VK_NEXT, VIRTUAL_KEY_NEXT },
	{ VK_END, VIRTUAL_KEY_END },
	{ VK_HOME, VIRTUAL_KEY_HOME },
	{ VK_LEFT, VIRTUAL_KEY_LEFT },
	{ VK_UP, VIRTUAL_KEY_UP },
	{ VK_RIGHT, VIRTUAL_KEY_RIGHT },
	{ VK_DOWN, VIRTUAL_KEY_DOWN },
	{ VK_SELECT, VIRTUAL_KEY_SELECT },
	{ VK_PRINT, VIRTUAL_KEY_PRINT },
	{ VK_EXECUTE, VIRTUAL_KEY_EXECUTE },
	{ VK_SNAPSHOT, VIRTUAL_KEY_SNAPSHOT },
	{ VK_INSERT, VIRTUAL_KEY_INSERT },
	{ VK_DELETE, VIRTUAL_KEY_DELETE },
	{ VK_HELP, VIRTUAL_KEY_HELP },
	{ '0', VIRTUAL_KEY_0 },
	{ '1', VIRTUAL_KEY_1 },
	{ '2', VIRTUAL_KEY_2 },
	{ '3', VIRTUAL_KEY_3 },
	{ '4', VIRTUAL_KEY_4 },
	{ '5', VIRTUAL_KEY_5 },
	{ '6', VIRTUAL_KEY_6 },
	{ '7', VIRTUAL_KEY_7 },
	{ '8', VIRTUAL_KEY_8 },
	{ '9', VIRTUAL_KEY_9 },
	{ 'A', VIRTUAL_KEY_A },
	{ 'B', VIRTUAL_KEY_B },
	{ 'C', VIRTUAL_KEY_C },
	{ 'D', VIRTUAL_KEY_D },
	{ 'E', VIRTUAL_KEY_E },
	{ 'F', VIRTUAL_KEY_F },
	{ 'G', VIRTUAL_KEY_G },
	{ 'H', VIRTUAL_KEY_H },
	{ 'I', VIRTUAL_KEY_I },
	{ 'J', VIRTUAL_KEY_J },
	{ 'K', VIRTUAL_KEY_K },
	{ 'L', VIRTUAL_KEY_L },
	{ 'M', VIRTUAL_KEY_M },
	{ 'N', VIRTUAL_KEY_N },
	{ 'O', VIRTUAL_KEY_O },
	{ 'P', VIRTUAL_KEY_P },
	{ 'Q', VIRTUAL_KEY_Q },
	{ 'R', VIRTUAL_KEY_R },
	{ 'S', VIRTUAL_KEY_S },
	{ 'T', VIRTUAL_KEY_T },
	{ 'U', VIRTUAL_KEY_U },
	{ 'V', VIRTUAL_KEY_V },
	{ 'W', VIRTUAL_KEY_W },
	{ 'X', VIRTUAL_KEY_X },
	{ 'Y', VIRTUAL_KEY_Y },
	{ 'Z', VIRTUAL_KEY_Z },
	{ VK_NUMPAD0, VIRTUAL_KEY_NUMPAD0 },
	{ VK_NUMPAD1, VIRTUAL_KEY_NUMPAD1 },
	{ VK_NUMPAD2, VIRTUAL_KEY_NUMPAD2 },
	{ VK_NUMPAD3, VIRTUAL_KEY_NUMPAD3 },
	{ VK_NUMPAD4, VIRTUAL_KEY_NUMPAD4 },
	{ VK_NUMPAD5, VIRTUAL_KEY_NUMPAD5 },
	{ VK_NUMPAD6, VIRTUAL_KEY_NUMPAD6 },
	{ VK_NUMPAD7, VIRTUAL_KEY_NUMPAD7 },
	{ VK_NUMPAD8, VIRTUAL_KEY_NUMPAD8 },
	{ VK_NUMPAD9, VIRTUAL_KEY_NUMPAD9 },
	{ VK_MULTIPLY, VIRTUAL_KEY_MULTIPLY },
	{ VK_ADD, VIRTUAL_KEY_ADD },
	{ VK_SEPARATOR, VIRTUAL_KEY_SEPARATOR },
	{ VK_SUBTRACT, VIRTUAL_KEY_SUBTRACT },
	{ VK_DECIMAL, VIRTUAL_KEY_DECIMAL },
	{ VK_DIVIDE, VIRTUAL_KEY_DIVIDE },
	{ VK_F1, VIRTUAL_KEY_F1 },
	{ VK_F2, VIRTUAL_KEY_F2 },
	{ VK_F3, VIRTUAL_KEY_F3 },
	{ VK_F4, VIRTUAL_KEY_F4 },
	{ VK_F5, VIRTUAL_KEY_F5 },
	{ VK_F6, VIRTUAL_KEY_F6 },
	{ VK_F7, VIRTUAL_KEY_F7 },
	{ VK_F8, VIRTUAL_KEY_F8 },
	{ VK_F9, VIRTUAL_KEY_F9 },
	{ VK_F10, VIRTUAL_KEY_F10 },
	{ VK_F11, VIRTUAL_KEY_F11 },
	{ VK_F12, VIRTUAL_KEY_F12 }
};

WORD virtual_key_to_wnd_vk[VIRTUAL_KEY_NUM] = {
	VK_LBUTTON,
	VK_RBUTTON,
	VK_CANCEL,
	VK_MBUTTON,
	VK_XBUTTON1,
	VK_XBUTTON2,
	VK_BACK,
	VK_TAB,
	VK_CLEAR,
	VK_RETURN,
	VK_SHIFT,
	VK_CONTROL,
	VK_MENU,
	VK_PAUSE,
	VK_CAPITAL,
	VK_HANGUL,
	VK_IME_ON,
	VK_JUNJA,
	VK_FINAL,
	VK_HANJA,
	VK_KANJI,
	VK_IME_OFF,
	VK_ESCAPE,
	VK_CONVERT,
	VK_NONCONVERT,
	VK_ACCEPT,
	VK_MODECHANGE,
	VK_SPACE,
	VK_PRIOR,
	VK_NEXT,
	VK_END,
	VK_HOME,
	VK_LEFT,
	VK_UP,
	VK_RIGHT,
	VK_DOWN,
	VK_SELECT,
	VK_PRINT,
	VK_EXECUTE,
	VK_SNAPSHOT,
	VK_INSERT,
	VK_DELETE,
	VK_HELP,
	'0',
	'1',
	'2',
	'3',
	'4',
	'5',
	'6',
	'7',
	'8',
	'9',
	'A',
	'B',
	'C',
	'D',
	'E',
	'F',
	'G',
	'H',
	'I',
	'J',
	'K',
	'L',
	'M',
	'N',
	'O',
	'P',
	'Q',
	'R',
	'S',
	'T',
	'U',
	'V',
	'W',
	'X',
	'Y',
	'Z',
	VK_NUMPAD0,
	VK_NUMPAD1,
	VK_NUMPAD2,
	VK_NUMPAD3,
	VK_NUMPAD4,
	VK_NUMPAD5,
	VK_NUMPAD6,
	VK_NUMPAD7,
	VK_NUMPAD8,
	VK_NUMPAD9,
	VK_MULTIPLY,
	VK_ADD,
	VK_SEPARATOR,
	VK_SUBTRACT,
	VK_DECIMAL,
	VK_DIVIDE,
	VK_F1,
	VK_F2,
	VK_F3,
	VK_F4,
	VK_F5,
	VK_F6,
	VK_F7,
	VK_F8,
	VK_F9,
	VK_F10,
	VK_F11,
	VK_F12
};